### ISSUE TITLE
Loading scene with "Wait for transition" set in view

### ISSUE THREAD

**Issue by mwebi** [JonathanReid/Scaffolding#1]
Hey Jon _waves_,

when loading a scene with like "RequestSceneWithView<ArtistStartView>(LoadSceneType.Load, "template_licenseOne_scene");" and the view is set as "Wait for previous transition hide" the loaded view stays disabled.

**Comment by mwebi** [comment]
LoadAsync is fine

**Comment by JonathanReid** [comment]
Fixed in commit 991b83a55a731e7a96fc956affc1ceaa908d540c
